swagger: "2.0"
info:
  version: "0.0.1"
  title: Slapi
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
x-a127-config: {}
x-a127-services:
  quota:     
    provider: volos-quota-memory
    options:
      timeUnit: minute
      interval: 1
      allow: 60
  cache:
    provider: volos-cache-memory
    options:
      name: hello-cache
      ttl: 60000
paths:
  /hello:
    # binds a127 app logic to a route
    x-swagger-router-controller: hello_world
    x-a127-apply:
      quota: {}
      cache:
          key:
            helper: cache
            function: setKey
    get:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: hello
      parameters:
        - name: name
          in: query
          description: The name of the person to whom to say hello
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  /hello2:
    # binds a127 app logic to a route
    x-swagger-router-controller: hello2_world
    x-a127-apply:
      quota: {}
      cache:
          key:
            helper: cache
            function: setKey
    get:
      description: Returns 'hello2' to the caller
      # used as the method name of the controller
      operationId: hello2
      parameters:
        - name: name
          in: query
          description: The name of the person to whom to say hello2
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/Hello2WorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
# complex objects have schema definitions
definitions:
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
  Hello2WorldResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  SpecResponse:
    required:
      - message
    properties:
      message:
        type: string
